abhisheknaiidu/awesome-github-profile-readme

- README.md
Bdougie has a MySpace-themed README. I think it is pretty cool!
https://twitter.com/bdougieYO/status/1281699715466199040?s=20
> Add bdougie

- README.md
He implemented an awesome feature, skill endorsements, just like on LinkedIn!
https://twitter.com/swyx/status/1281752510458286080
> Add @sw-yx

- README.md
- Added my README to Typing section
- Added Shields Project to Tools
> ➕ Added a README & a tool

- README.md
I have placed it under simple yet efficient because this is something easy to create and has a deep impact on the people visiting the profile.
> I have added my version of readme.md

- README.md
I added a new category because I couldn't think of where else to put it. If you think it fits in one of the existing categories, please suggest and I'll move it there. I'm hoping this looks good enough. :)
@hussainweb
> Add Hussainweb to the list of repos

- README.md
Added my readme profile to Simple but Innovative
> Added My Readme Profile

- README.md
Fancy Fonts
https://github.com/xiaoluoboding/xiaoluoboding
> Add xiaoluoboding.md

- README.md
- [x ] 🚩 Other
Added " // " to the url of an earlier commit which caused 404 
https://github.com/PluckyPrecious/PluckyPrecious
> fixed an error

- README.md
Add article with supported and unsupported feature.
https://github.com/torrocus
> Add article about special GitHub repo

- README.md
I made a little `Roll For Initiative` game for my readme and thought I'd share.
https://github.com/benjaminsampica/benjaminsampica
> Added Ben Sampica's `roll for initiative` under game mode

- README.md
Mike's README is entirely automated by a GitHub action
https://github.com/mscoutermarsh/mscoutermarsh
> Add Mike Coutermarsh's profile

- README.md
Added the contents at the top of the README file,
makes it easier to navigate when list gets longer
[ABSphreak](https://github.com/ABSphreak)
> ➕ Added Contents list at the top

- README.md
Added Hemant Joshi's README.md username: @8bithemant
Hemant Joshi's readme with Dynamic Looks
https://github.com/8bithemant/8bithemant
> Added Hemant Joshi's Readme

- README.md
Fixed the PR and Issues badges
from 
to
> 🔧 Fixed PR & Issues Badge

- README.md
- Centered the heading styles
- Ported Markdown to HTML for headings and badges
- Introduced [dwyl](http://hits.dwyl.io/) hits instead of [glitch](https://visitor-badge.glitch.me/) visitor badge, but it is disabled because it does not line up with the styles of other badges
from:
to:
Let me know if you want me to change something in my PR.
> ✨ Centering the Header

- README.md
Added my GitHub profile README repo and the corresponding article
https://github.com/mokkapps/mokkapps
> Added my GitHub profile README repo and the corresponding article

- README.md
Added a profile readme in the simple section.
https://github.com/MarikIshtar007/MarikIshtar007
> Added Profile : Haany Ali

- README.md
> Add my profile to Github Actions' list

- README.md
I feel it's simple yet innovative.
An innovative design with some cult of party parrots.
[Anurag Singh](https://github.com/ashleymavericks)
> Added new profile under simple yet innovative

- README.md
A new profile is added under the Minimalistic category.
https://github.com/pr2tik1/pr2tik1
> Add new profile in Minimalistic

- README.md
Added the profile of Kavish Hukmani to Game Mode
Added my profile which allows you to play a game of Tic-Tac-Toe by clicking on the tiles.
The turns alternate and last an hour each. The most picked move is chosen at the end of each hour.
https://github.com/DoubleGremlin181
> Added Kavish Hukmani's Profile

- README.md
I added my readme to it.
https://github.com/dephraiim/dephraiim
> Added Duncan

- README.md
🚀 Improved Community Badge, Added Contributors Badge
> 🚀 Improved Community Badge, Added Contributors Badge

- .github/PULL_REQUEST_TEMPLATE.md
Added Discord Badge to template
> Added Discord Badge to template

- .github/PULL_REQUEST_TEMPLATE.md
> Updated PR Template ✨

- README.md
- Added profiles of [gautamkrishnar](https://github.com/gautamkrishnar/gautamkrishna) & [athul](https://github.com/athul/athul)
- Added tool → [Dev Metrics in Readme](https://github.com/athul/waka-readme)
[ABSphreak](https://github.com/ABSphreak)
> ➕ Added a tool and 2 new profiles

- README.md
Hi Abhishek,
thanks for the nice compilation of cool profile readme repositories!
I'd be happy to be on your list.
Thanks and best regards,
Dennis
In this PR I added my own profile to the **descriptive** category. My profile consists of a large header banner image and a short description about myself plus some custom badges. I also added a short tutorial to my profile how to build your own profile readme repository and put a link to your curated list into it.
https://github.com/DennisHartrampf/DennisHartrampf
> Add DennisHartrampf to descriptive category

- README.md
Add "Profile Activity Generator" tools
https://github.com/omidnikrah
> Add "Profile Activity Generator" tools

- README.md
Added new name in Anime Section
[AbhiSaphire](https://github.com/AbhiSaphire)
> Added new name in Anime Section

- README.md
Add my [personal GitHub Profile README](https://github.com/roaldnefs/roaldnefs) under the GitHub Actions sections. It uses GitHub Actions to read a RSS feed of my blog to dynamically add all blog posts to my README file.
[roaldnefs](https://github.com/roaldnefs)
> Add Roald Nefs in GitHub Actions category

- README.md
- Added self
- Ran prettier on the readme for consistent formatting
https://github.com/peterthehan
> Add name to Icons section

- README.md
New profile
[https://github.com/aemmadi](https://github.com/aemmadi)
> Added New Profile

- README.md
- Added my profile
- Added a profile view counter ready-to-go package for Laravel
https://github.com/caneco
> Added my proofile and a count visits package

- README.md
Added @Rishit-dagli under simple but innovative README's
https://github.com/Rishit-dagli/
> Added Rishit Dagli README

- README.md
Add new name in "Just Images" section
Look at my picture 😄 
https://github.com/7ma7X
> Add new name in "Just Images" section

- README.md
Added my article about how I built simonw/simonw with GitHub Actions
https://github.com/simonw
> Added my article about how I built simonw/simonw

- README.md
This links to a quick "how-to" on adding a 1990s style counter to your GitHub profile. 
See it live in this PR or in [my GitHub profile](https://github.com/ryanlanciaux).
> Adds 1990s style visitor counter

- README.md
> 🚀 Updating from new fork : Adding Tool ➕

- README.md
I added under "minimalistic" flag my github profile to share its layout to others.
Please tell me if you need anythings, I stay tune ! 👌
[Mrstandu33/MrStandu33](https://github.com/MrStanDu33/MrStanDu33)
> ✨ add MrStanDu33 profile @ Minimalistic

- README.md
[Github Profile README Generator](https://github.com/rahuldkjain/github-profile-readme-generator) by @rahuldkjain - This tool provides an easy way to create github profile readme with latest addons like `visitors count`, `github stats` etc.
rahuldkjain
> ➕ Added another Tool

- README.md
A GitHub action to add the commits of your featured repositories to your profile page.
https://github.com/umutphp
> Add Dynamic Profile Page Action to tool list

- README.md
Adding the new name in "GIFS" section.
https://github.com/demartini
> Add Demartini's Profile

- README.md
My profile. If it doesn't load, try refreshing some times. It loads eventually.
https://github.com/sindresorhus
> Add Sindre Sorhus

- README.md
> Add a new profile under 'Simple but Innovative Ones'

- README.md
Adding JonathanGin52 to the Game mode category. My profile features a small little asynchronous connect four game.
https://github.com/JonathanGin52
> Add JonathanGin52 to Game mode

- README.md
- [] 📝 Documentation Update
Added my profile to descriptive category
https://github.com/garimasingh128
> Added Garima Singh to Descriptive category

- README.md
Added Fatih Kadir Akın's blog to Simple but Innovative Ones.
https://github.com/f
> Add @f to Simple but Innovative Ones

- README.md
Added Readme under the Icons category
[Readme](https://github.com/Thomas-George-T/Thomas-George-T)
> Added readme under Icons

- README.md
Adding Derek Nguyen's profile to the **Simple but Innovative Ones** category. My profile is simple but unique.
https://github.com/dereknguyen269
> Add Derek Nguyen to Icons

- README.md
A simple gif profile for lazy programmers.
https://github.com/okankocyigit
> Add Lazy Programmer Profile

- README.md
Added Lucas Vazquez README.md
github username: @lucasvazq
Lucas Vazquez Readme
I found it creative but I prefer to say it's descriptive
https://github.com/lucasvazq
> Added Lucas Vazquez Readme

- README.md
Add `npm statistics` downloads repo
https://github.com/maddhruv
> feat: add maddhruv

- README.md
I added my own profile README.md
> Add my profile README

- README.md
> Add 小弟调调™'s profile.

- README.md
I want to add myself to the _Descriptive_ section lol :laughing: 
<https://github.com/you-create>
> Add you-create's to the Descriptive section

- README.md
Fixes clicking on the `Minimalistic` link in the README table of contents.
[Profile](https://github.com/smhutch)
> Fix `minimalistic` anchor

- README.md
It's a minimalistic profile with a header image 
https://github.com/jayrajroshan/jayrajroshan
> Added Jayraj Roshan's profile under Minimalistic

- README.md
I added my simple and minimalistic profile to the Minimalistic section of the README.
[https://github.com/amxchang/amxchang](https://github.com/amxchang/amxchang)
> Added amxchang to Minimalistic

- README.md
Added my tutorial on creating interactive READMEs
[Link](https://kavishhukmani.me/github-profile-interactive-readme-tutorial/) for said tutorial
https://github.com/DoubleGremlin181
> Added article on creating interactive READMEs

- README.md
Added line 159
Added line 66
- [✔️ ] 🚀 Added Name
- [✔️ ] 🚩 Other
Added my own profile name
and added the new tool for waka time readme
https://github.com/anmol098
> 🚀 Added anmol098 🚩 Added tool for profile readme

- README.md
Add my profile repo, which has some fun badges
https://github.com/br3ndonland
> Add Brendon Smith to badges section

- README.md
Added my readme to the github actions section. 
Feel free to add it to another section if you think it is more appropriate!
https://github.com/JessicaLim8
> Add Jessica Lim to Github Actions section

- README.md
> Add my README in "Simple but Innovative" section

- README.md
A profile which is generated by Github Action, and I will keep enhancing it.
https://github.com/liununu/liununu
> Add liununu to Github Actions section

- README.md
Realtime Spotify playing card in profile
https://github.com/kittinan
> Add my README in "Dynamic Realtime" section

- README.md
I consider my profile fairly minimal
[Maximous Black](https://github.com/maximousblk/maximousblk)
> maximousblk

- README.md
Badges used for programming languages and link to user repositories in those languages
Example of badges used for programming languages and link to user repositories in those languages, along with other badges.
https://github.com/alwinw
> Add alwinw

- README.md
Add xrkffgg
- https://github.com/xrkffgg
- https://github.com/xrkffgg/xrkffgg
> Add xrkffgg

- README.md
Add monkindey
* https://github.com/monkindey
* https://github.com/monkindey/monkindey
> add Kiho Code Mode

- README.md
> :sparkles: add tw93 and Tools and Articles

- README.md
I think my profile is unique or at least cool, so I decided to give it a try and pull request
https://github.com/MartonDev
> Add me to readme :)

- README.md
Get favorites Anime, Manga, Characters from Anilist.co
https://github.com/moepoi
> Simple README profile with Github Actions

- README.md
Added a extended description of to the github action to help to understand that better.
- [✅] 📝 Documentation Update
- [✅] 🚩 Other
> Updated GitHub action tool

- README.md
Add Spotify now playing card generator tool
https://github.com/kittinan/spotify-github-profile
> add spotify now playing tool

- README.md
Crosswords are technically a game, but this is not interactive.
So, minimalistic it is I guess!
[https://github.com/AlexMartinFR](https://github.com/AlexMartinFR)
> Adds Alex Martin

- README.md
Added my readme to the github simple but innovative section.
Let me know if it belongs in another section!
https://github.com/novatorem
> Add Andrew Novac to Simple but Innovative section

- README.md
> Add a new category: A Little Bit of Everything! 😃

- README.md
Let me know what you think of it >.<
A self updating "latest releases" section and a small, funny and humorous bio
https://github.com/alx365
> Added my profile README to the descriptive section

- README.md
- [ *] 🚀 Added Name
Added my README profile link to the GIF section.
https://github.com/RaghavK16/RaghavK16
> Add README profile link

- README.md
Add halfrost to Descriptive & Simple but Innovative Ones
https://github.com/halfrost/halfrost
> Add halfrost to Descriptive & Simple but Innovative Ones

- README.md
Added a "Retro" section + Added GitHub users fnky and brunnerlivio to retro section
>  Add new category - Retro 😎

- README.md
Add my profile to the Github Actions 🤖 category.
[qu4k/qu4k](https://github.com/qu4k/qu4k)
> chore: add qu4k suggestion

- README.md
Add GitHub Profile to Badges category
https://github.com/ileriayo/ileriayo
>  Add GitHub Profile to Badges category

- README.md
I've added my minimalistic and simple GitHub profile link to [README.md](https://github.com/abhisheknaiidu/awesome-github-profile-readme/blob/master/README.md)
https://github.com/orhun
> doc: Add Orhun's profile to README.md

- README.md
Added https://github.com/gautamkrishnar/blog-post-workflow
> Added blog-post-workflow action

- README.md
Added Spiderpig86 (me) to profiles that use Github Actions.
https://github.com/Spiderpig86
> Added Spiderpig86 to Github Actions 🤖

- README.md
My profile uses GitHub Actions to display my followers with the most followers.
It also uses [athul/waka-readme](https://github.com/athul/waka-readme).
[ouuan](https://github.com/ouuan)
[ouuan/ouuan](https://github.com/ouuan/ouuan)
> Add ouuan (Yufan You)

- README.md
> Add Github Readme LinkedIn

- README.md
My profile updates photo daily from https://www.dailyrandomphoto.com/ .
https://github.com/dailyrandomphoto
> Add Daily Random Photo

- README.md
Readme with github actions with no separate blog required for updating TILs. Completely within the github ecosystem.
https://github.com/vidyabhandary/vidyabhandary
> Add link of Github profile

- README.md
i added my proile in descriptive catagory on your recommndations
[https://github.com/keshavsingh4522](https://github.com/keshavsingh4522)
[keshavsingh4522/keshavsingh4522](https://github.com/keshavsingh4522/keshavsingh4522)
> Add profile

- README.md
> C9-LinkRs profile in Dynamic real time section

- README.md
Add my profile in Gif section. It will never gonna let you down. I promise :smiley: 
https://github.com/KevCui/KevCui
> Add Kevin Cui

- README.md
Add Profile README Widgets tool.
> add profile readme widgets tool

- README.md
Example of personalized header, GIFs, emojis, customized badges and GitHub README Stats - Little bit of everything.
https://github.com/MartinHeinz
> Add MartinHeinz profile.

- README.md
Add profile https://github.com/RaoHai/RaoHai.
And An article "How I Built A Self-Updating README by Webhooks and Netlify Functions" .
https://github.com/RaoHai/RaoHai
> feat: add Raohai/Raohai

- README.md
Referencing another pull, changing categories:
https://github.com/abhisheknaiidu/awesome-github-profile-readme/pull/113
https://github.com/novatorem
> Moved from Simple to Dynamic

- README.md
Add ridermansb into Minimalistic
> add ridermansb

- README.md
Add my GitHub profile.
https://github.com/ChungZH/ChungZH/
> add chungzh

- README.md
Using Node.js to generate your own github profile readme.
[@Elon Tang(blackcater)](https://github.com/blackcater/blackcater)
> Add blackcater profile

- README.md
Show your latest Medium article on your readmes!
https://github.com/omidnikrah/github-readme-medium
https://github.com/omidnikrah/
> Add "GitHub Readme Medium"

- README.md
Hey, this is Akshit, and I added my profile in the GitHub actions section. My README updates every 1 hour using a scheduled cron jon using actions, changing my spotify stats and the quote of the hour
[Akshit Garg (@gargakshit)](https://github.com/gargakshit)
> Add mine (@gargakshit)'s README to the list

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Dynamic profile showing current Spotify song, top spotify songs for varying time range, current games on chess.com and a list of icons of skills!
Music bars for song are colored based on the songs danceability, energy, and happiness, and move to the tempo of the song!
Inspired by [natemoo-re](https://github.com/natemoo-re)
[https://github.com/andyruwruw](https://github.com/andyruwruw)
> Dynamic Profile with Spotify and Chess.com APIs :)

- README.md
> docs: add Leo's profile

- README.md
Another eye-catching entry to the Anime Section
https://github.com/Xx-Ashutosh-xX/Xx-Ashutosh-xX
> Add Ashutosh profile

- README.md
Let me know if a different category is more suitable 🙂
https://github.com/hedythedev
> Add my profile to a little bit of everything

- README.md
> muskanrani

- README.md
Add new article to the list - [Build a Stunning README For Your GitHub Profile](https://towardsdatascience.com/build-a-stunning-readme-for-your-github-profile-9b80434fe5d7)
> Add article - Build a Stunning README For Your GitHub Profile.

- README.md
I discovered this repository a week ago and was amazed at what people had done with a feature that I didn't even know existed. I was especially impressed by @timburgan's profile, which was hosting a chess game. I thought that was amazing and knew I had to join in.
It's been great fun — I've spent the past week hacking away, playing with the GitHub API and learning a lot about Git internals that I would never have appreciated otherwise. Thank you, Abhishek, for creating this repository, because without it I never would have learned the skills I needed to make this.
My profile is now hosting an open [Royal Game of Ur](https://en.wikipedia.org/wiki/Royal_Game_of_Ur), an ancient game dating back to 2600 BCE, and whose rules we can never be quite sure that we know — because _everyone_ played …
> You can play The Royal Game of Ur on my profile

- README.md
> Add "GitHub Readme StackOverflow"

- README.md
I've added my GitHub readme profile to the list :wink:
It contains dynamically generated readme using Github actions & I'll add more features to it soon. 
https://github.com/jatin2003/jatin2003
> Add Jatin's Profile

- README.md
- [* ] 🚀 Added Name
Closed the previous pull request that caused merge conflict.
[Redowan Delowar](https://github.com/rednafi/rednafi)
> Added rednafi and fixed merge conflict

- README.md
A minimalist profile readme that blends in with the rest of your profile page 
https://github.com/Aveek-Saha
> Add Aveek Saha's readme

- README.md
> Aditya Pal - A Little Bit of Everything :)

- README.md
Adding my profile into the `Anime 👾` section.ヾ(•ω•`)o
Edison Lee (@edisonlee55)
> Add edisonlee55's Profile

- README.md
My profile uses a github [action](https://github.com/marketplace/actions/profile-readme-stats) that updates the stats and languages every 12h.
https://github.com/teoxoy
> add my profile

- README.md
Add [Profile Readme Stats](https://github.com/marketplace/actions/profile-readme-stats) - Showcase your github stats on your profile README.md
> Add 'Profile Readme Stats' [Github Action]

- README.md
Adding my generator tool https://github.com/arturssmirnovs/github-profile-readme-generator
> Adding generator tool

- README.md
Hey, I`ve updated my profile, can I join the Community? I will keep updating my profile and make it Better!
https://github.com/xunzhuo/
> Add Xunzhuo`s Profile

- README.md
Add the article "How I added my Spotify statistics to my GitHub readme 📜" published by me on dev.to
https://github.com/gargakshit
> Add a dev.to article by me

- README.md
I have updated two entries for Badge and simple profiles. I have added some new badges like - Express, graphql, Jenkins, VS code, shell, and many more
https://github.com/moshfiqrony
> MR | Simple and badge profile list updated

- README.md
[README Jokes](https://github.com/ABSphreak/readme-jokes) - Random dev jokes in GitHub README.
[ABSphreak](https://github.com/ABSphreak)
> ➕ Add a new Tool

- README.md
Added my Github profile "d-koppenhagen" wich uses Github action to fetch some blogpost data.
https://github.com/d-koppenhagen/d-koppenhagen
> feat: add GH profile from d-koppenhagen

- README.md
How to Create a Self-Updating README.md for Your GitHub Profile
- [x ] 🚩 Other
Add a new article to the list:
[How to Create a Self-Updating README.md for Your GitHub Profile](https://medium.com/@th.guibert/how-to-create-a-self-updating-readme-md-for-your-github-profile-f8b05744ca91)
[thmsgbrt](https://github.com/thmsgbrt)
> Add a new article to the List

- README.md
Added some links to youtube video tutorials for creating impressive profile readme.
also added the Youtube Channel also by giving -
and also mentioned Video Tutorial at the top where all categories are mentioned.
https://www.github.com/PrathmeshSadake
> Created a Video Tutorial Section

- README.md
Added my profile under the Actions category and also my video under Tutorials.
[codeSTACKr](https://github.com/codestackr)
> Added codeSTACKr profile and video

- README.md
- [x ] 🚀 Added Name
Added my Github README.md profile 
https://github.com/minoveaz
> added Minoveaz README.md

- README.md
I've updated my Github Profile, including a counter like a divergence meter. Can you add my link to the list? 
https://github.com/cxyfreedom/cxyfreedom
> Add cxyfreedom's profile

- README.md
Animated SVG in the style of my work-in-progress website that looks crisp on any resolution with a rainy vibe to it.
https://github.com/vaaski
<div align="center">
<a href="https://vaaski.dev">
</a>
</div>
> add vaaski/vaaski to Simple but Innovative Ones

- README.md
> Add xcaq/xcaq to "Dynamic Realtime" category.

- README.md
Added my name to the Game Mode section.
https://github.com/kylepls
> Add my profile to Game Mode

- README.md
The GitHub readme is connected to my Trello board and updates my active projects in Realtime
The GitHub readme is connected to my Trello board and displays my current active projects in Realtime
https://github.com/DaniAkash
> added Dani Akash to Dynamic Realtime list

- README.md
Hey! I'm currently only embedding a GIF but I may add more Github-like stuff around it in the future in order to push the actual contribution graph a little further down on bigger screens.
https://github.com/nilfalse
> Add @nilfalse

- README.md
Hi, just created this profile, hoping can bring some inspiration to others 😸 
If you feel that needs to be in another category, just let me know ><
Thanks! 🧤 
https://github.com/KelviNosse
> Adding "KelviNosse"

- README.md
This is my profile readme. I have tried to add a little bit of everything in this. Also my future work will include it to connect to chess.com. It also has a bar that updates dynamically using github workflows.
https://github.com/apoorvtyagi
> Add Apoorv's Profile Readme to "Little bit of everything"

- README.md
Added `khalby786/khalby786` under the section 'A Little Bit of Everything' and added a new tool - https://github.com/khalby786/REHeader
https://github.com/khalby786/khalby786
> Add khalby786/khalby786 & tool 

- README.md
Added a new article on creating a README
https://medium.com/swlh/how-to-make-your-github-profile-shine-using-profile-readmes-2405a742393c
Linked it to your repository as well so that people can check it out for inspiration!
https://github.com/JessicaLim8
> Add new article on how to create READMEs

- README.md
Added my name in Dynamic Realtime and Gitwar Profile Score in Tools
[https://github.com/iampavangandhi](https://github.com/iampavangandhi)
> Added My Name and Gitwar Profile Score Tool in README.md

- README.md
Added Name of my repo to the list
https://github.com/Defcon27
> Added a name to " Simple but Innovative Ones"

- README.md
My README Profile is simple, eye-catching, with a "Get in Touch" sections for contacts and statistics chart.
https://github.com/federico-dondi
> Federico Dondi - Added profile to Minimalistic

- README.md
This tool can generate a website's PageSpeed score in svg format. This svg is animated and can be attached to GitHub README which looks good upon viewing.
An example: https://github.com/ankurparihar/ankurparihar.github.io#readme
[PageSpeed score](https://github.com/ankurparihar/readme-pagespeed-insights) - Generate website's PageSpeed score in animated svg form which can be used in GitHub README
@ankurparihar
> Added pagespeed-insights tool

- README.md
Added my profile under descriptive section
https://github.com/vidursatija
> Added [Vidur Satija](my profile) under descriptive section

- README.md
1. Added my profile under Dynamic Realtime section
2. Corrected andyruwruw's name to Andrew Young
https://github.com/rusty-sj
> Added Rashmi Jadhav profile and corrected someone's name

- README.md
I think it's a little good design :)
[zumrudu-anka](https://github.com/zumrudu-anka)
> Added zumrudu-anka

- README.md
My readme profile
https://github.com/onimur/onimur
> Add Onimur readme

- README.md
My readme profile has been added.
https://github.com/Coordinate-Cat/Coordinate-Cat
> Added "Oka" README.md

- README.md
- [ ✔] ✅ Joined Community
https://github.com/Terabyte17
> Added [Yash Sahijwani] under Simple but Innovative

- README.md
Added my GitHub profile readme link under the GIF category.
[https://github.com/rishavanand/rishavanand](https://github.com/rishavanand/rishavanand)
> added "rishavanand" under gif category

- README.md
**Added GitHub Profilinator**
This tool contains small GUI components that you can hook together to generate markdown for your perfect readme.
- [Repo link](https://github.com/rishavanand/github-profilinator)
- [Live demo link](http://profilinator.rishav.dev/)
[Rishav Anand](https://github.com/rishavanand)
> ➕ add GitHub Profilinator under tools

- README.md
Added GitHub Readme Quotes under tools.
[Github](https://github.com/PiyushSuthar/github-readme-quotes)
> Add: GitHub Readme Quotes under Tools

- README.md
Add **Tushar Mittal profile** in the **Little bit of everything section**, and **random meme generator** in the **Tools** section. 
[https://github.com/techytushar/techytushar](https://github.com/techytushar/techytushar)
> Add Tushar Mittal profile and Random Meme tool

- README.md
My readme profile has been added.
https://github.com/lifeparticle
> Added lifeparticle

- README.md
[Github Readme Twitter](https://github.com/gazf/github-readme-twitter) - Show your latest tweet on your readme.
[gazf](https://github.com/gazf)
> Add a new tool by gazf

- README.md
add a lot of funny things and show more information
https://github.com/itgoyo/itgoyo
> add itgoyo'profile in Github Actions

- README.md
Hi I propose my profile to add into the list.
I made a simple profile with some badges
https://github.com/Char-Al
> Add char-al profile

- README.md
Adding my personal profile under Dynamic Realtime. The main feature is an automatically updated ASCII graph featuring coding stats. It also uses Wakatime, like many others, but the pipeline and general look and feel is completely new.
https://github.com/MacroPower
> Add "Jacob Colvin" profile to "Dynamic Realtime"

- README.md
Added [Zhenye Na](https://github.com/Zhenye-Na/Zhenye-Na)
> Suggested Github Profile README

- README.md
Thank you!  Your repo has given me so much inspiration
Added Sy Rashid to A Little Bit of Everything
[Sy Rashid](https://github.com/syrashid/syrashid)
> UPDATE: Added Sy Rashid

- README.md
Added "TheAbbie" To Descriptive README
[TheAbbie](https://github.com/theabbie)
> Added "TheAbbie" To Descriptive README

- README.md
had long since deleted my fork after i sent my pull request. so here is an updated version for #272
> update for #272

- README.md
Added my new StackOverflow badge repo for others to use!
https://github.com/claytonjhamilton/stackoverflow-badge
> Add: StackOverflow badge

- README.md
I've put many hours into my profile README, working on the format, layout, custom GitHub Actions, and more. The final result is something I'm extremely proud of.
I've opened this PR to add my profile to the list because I believe that it's a good example for someone just getting started on writing a profile README. I also believe that there are new things some people could potentially learn from it if they view the source.
[@cheesits456](https://github.com/cheesits456)
> Add cheesits456 to profile list

- README.md
***
***
Added my GitHub profile readme link under A Litte Bit of Everything category.
Thank you for creating this project and let me know how interesting the github personal page can be.😄
***
https://github.com/Jackyu-1999/Jackyu-1999
> Added my github profile to A Little Bit of Everything category

- README.md
Thank you for considering the addition of my profile to your list!
https://github.com/claytonjhamilton
> Add: Clayton Hamilton

- README.md
Added Raphael Ebner's github readme to badges category.
https://github.com/rafi0101
> ADD rafi0101 to badges category

- README.md
Added my profile to the **GIFS** section. Hope it's good enough. 😃
https://github.com/ShahriarShafin
> Add [Shahriar Shafin] to GIFS category

- README.md
PR to add my profile to Dynamic Realtime section.
The highlight of my profile README is that it looks good in both light mode as well as dark mode.
https://github.com/rahul-jha98
> add profile [rahul-jha98] to Dynamic Realtime section

- README.md
Add GitHub Profile Trophy
https://github.com/ryo-ma/github-profile-trophy
> 🏆Add GitHub Profile Trophy to Tools

- README.md
Showcases a minimalistic profile making use of badges and icons and some neat markdown tricks.
- https://github.com/moertel
> Add @moertel to "Minimalistic" section

- README.md
Added my profile to the `Simple but Innovative Ones` section. 
I hope it's enough to make part of this awesome curated list. :blush:
[Bruno Tacca](https://github.com/brunotacca)
> added [brunotacca] to Innovative Ones

- README.md
Added my profile to the `GIFS` section.
I hope it's enough to be part of this awesome curated list :)
[SP-XD](https://github.com/SP-XD/SP-XD
)
> Added [SP-XD] to GIFS

- README.md
You can play Pokémon: Red together with other visitors in this profile:
https://github.com/HFO4
> Add "Aaron Liu" to Game Mode category

- README.md
Thank you for considering to add my GitHub profile README to your list. I developed an interactive Chess game using GitHub Actions and Python 3. I hope you find it interesting and have fun playing there!
@marcizhu (https://github.com/marcizhu)
> Added Chess GitHub profile to Game Mode section

- README.md
Added profile Ksenia Morozova to GIFs.
[kmoroz](https://github.com/kmoroz)
> Added [kmoroz] to GIFS 👻

- README.md
- [X ] 🚀 Added Name
Added tool for sharing the book you are currently reading in GoodReads in your GitHub profile README.
https://github.com/thefr1nge
> GoodReads book status addeed to Tools Section

- README.md
Fixed a typo in one of the hyperlinks
> Fix a Typo

- README.md
Added my profile to the "Icons" category
https://github.com/vbriand
> Add Valentin Briand to Icons

- README.md
Added my name under Simple but Innovative Ones.
https://github.com/Wrapperup
> Added [Matthew Taylor] to Simple but Innovative Ones

- README.md
Added a link to Rak Laptudirm's Github profile `README.md`
[Rak Laptudirm](https://github.com/raklaptudirm)
> Added `Rak Laptudirm` under A Little Bit of Everything 😃

- README.md
Added my github profile to the list under minimalist category.
https://github.com/kha7iq/kha7iq
> docs: added profile under minimalistic

- README.md
* Added profile with Dynamically generated stats and video feed with lots of tables.
* Added Dynamic GitHub Streak Stats repo link to tools
* Added YouTube stats badge repo link to tools
* Added Readme Typing SVG repo to tools
**Profile:** https://github.com/DenverCoder1
**Tool 1:** GitHub Readme Streak Stats - https://github.com/DenverCoder1/github-readme-streak-stats
🔥 Stay motivated and show off your contribution streak! 🌟 Display your total contributions, current streak, and longest streak on your GitHub profile README
**Tool 2:** YouTube Channel stats - https://github.com/DenverCoder1/github-readme-youtube-stats
📺 Display number of subscribers on YouTube and/or your channel's view count as a badge
**Tool 3:** Readme Typing SVG - https://github.com/DenverCoder1/readme-typing-svg
:zap: …
> Added streak stats, YouTube stats, typing svg tools

- README.md
Descriptive 🗒
https://github.com/dayyass/dayyass
> Add Dani El-Ayyass to Descriptive

- README.md
As I already mentioned in this issue https://github.com/abhisheknaiidu/awesome-github-profile-readme/issues/689, there's a broken link, so I deleted it.
> Delete Kaito Sugimoto's readme profile

- README.md
Added my profile(Trini B) in README.MD. It has a bit of everything.  Also in `file edit mode` I have commented the links/sources of the features/customization😎 to make life easier for y'all....
https://github.com/trinib/trinib
> Epic profile added to "A Little Bit of Everything"

- README.md
Adding Nanra profile under Descriptive category
https://github.com/Nanra
> Add Nanra profile under Descriptive category
